# Generated by Django 5.2.5 on 2025-08-19 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aprendices", "0002_alter_aprendiz_options_remove_aprendiz_programa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("nit", models.CharField(max_length=50, unique=True)),
                ("direccion", models.CharField(max_length=300)),
                ("ciudad", models.CharField(max_length=50)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="EtapaPractica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tutor", models.CharField(max_length=200)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("objetivos", models.TextField(blank=True)),
                ("bitacora", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("LECTIVA", "En etapa lectiva"),
                            ("PRODUCTIVA", "En etapa productiva"),
                            ("FINALIZADO", "Formación finalizada"),
                            ("RETIRADO", "Retirado"),
                            ("APLAZADO", "Aplazado"),
                        ],
                        default="LECTIVA",
                        max_length=15,
                    ),
                ),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aprendices.aprendiz",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="etp_practica.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de Práctica",
                "verbose_name_plural": "Etapas de Práctica",
            },
        ),
    ]
