# Generated by Django 5.2.5 on 2025-08-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0002_alter_aprendiz_options_remove_aprendiz_programa_and_more"),
        ("etp_practica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsignacionAprendiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_confirmacion", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_inicio_propuesta",
                    models.DateField(
                        help_text="Fecha propuesta para iniciar la etapa práctica"
                    ),
                ),
                (
                    "fecha_fin_propuesta",
                    models.DateField(
                        help_text="Fecha propuesta para finalizar la etapa práctica"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de asignación"),
                            ("ASIGNADO", "Asignado a empresa"),
                            ("CONFIRMADO", "Confirmado por empresa"),
                            ("RECHAZADO", "Rechazado por empresa"),
                            ("INICIADO", "Etapa práctica iniciada"),
                            ("CANCELADO", "Asignación cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("REMOTO", "Trabajo remoto"),
                            ("HIBRIDO", "Modalidad híbrida"),
                        ],
                        default="PRESENCIAL",
                        max_length=15,
                    ),
                ),
                (
                    "tutor_propuesto",
                    models.CharField(
                        help_text="Nombre del tutor que supervisará al aprendiz",
                        max_length=200,
                    ),
                ),
                (
                    "area_trabajo",
                    models.CharField(
                        blank=True,
                        help_text="Área o departamento donde trabajará",
                        max_length=100,
                    ),
                ),
                (
                    "objetivos_propuestos",
                    models.TextField(
                        blank=True,
                        help_text="Objetivos específicos para la etapa práctica",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre la asignación",
                    ),
                ),
                (
                    "contacto_empresa",
                    models.CharField(
                        blank=True,
                        help_text="Persona de contacto en la empresa",
                        max_length=200,
                    ),
                ),
                ("telefono_contacto", models.CharField(blank=True, max_length=15)),
                (
                    "email_contacto",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contacto en la empresa",
                        max_length=254,
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.CharField(
                        blank=True,
                        help_text="Usuario que creó la asignación",
                        max_length=100,
                    ),
                ),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="aprendices.aprendiz",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_aprendices",
                        to="etp_practica.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Aprendiz",
                "verbose_name_plural": "Asignaciones de Aprendices",
                "ordering": ["-fecha_asignacion"],
            },
        ),
        migrations.AddField(
            model_name="etapapractica",
            name="asignacion_origen",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etapa_practica_creada",
                to="etp_practica.asignacionaprendiz",
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionaprendiz",
            index=models.Index(fields=["estado"], name="etp_practic_estado_060ade_idx"),
        ),
        migrations.AddIndex(
            model_name="asignacionaprendiz",
            index=models.Index(
                fields=["fecha_asignacion"], name="etp_practic_fecha_a_caead5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionaprendiz",
            index=models.Index(
                fields=["aprendiz", "estado"], name="etp_practic_aprendi_fb91e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionaprendiz",
            index=models.Index(
                fields=["empresa", "estado"], name="etp_practic_empresa_53cbc1_idx"
            ),
        ),
    ]
